document.addEventListener("DOMContentLoaded", function () {
  // hangman game

  //credit to https://cpb-us-w2.wpmucdn.com/u.osu.edu/dist/f/100615/files/2020/12/Final-Code.pdf for list of words
  var words = [
    "electricity",
    "donkey",
    "hardware",
    "xerox",
    "transistor",
    "computer",
    "desktop",
    "engineering",
    "hangman",
    "circuit",
    "imagination",
    "robot",
    "memory",
    "power",
    "submarine",
    "chess",
    "resistance",
    "matrix",
    "function",
    "laser",
    "mechanism",
    "bodyguard",
    "titanic",
    "global",
    "ozone",
    "bridge",
    "technology",
    "spider",
    "pyramid",
    "sphere",
    "member",
    "warning",
    "yourself",
    "screen",
    "language",
    "system",
    "internet",
    "parameter",
    "traffic",
    "network",
    "filter",
    "nucleus",
    "automatic",
    "microphone",
    "cassette",
    "operation",
    "country",
    "beautiful",
    "picture",
    "teacher",
    "superman",
    "undertaker",
    "alarm",
    "process",
    "keyboard",
    "electron",
    "certificate",
    "grandfather",
    "landmark",
    "relativity",
    "eraser",
    "design",
    "football",
    "human",
    "musician",
    "egyptian",
    "elephant",
    "queen",
    "message",
    "wallpaper",
    "nationality",
    "answer",
    "wrong",
    "statement",
    "forest",
    "puzzle",
    "voltage",
    "current",
    "mathematics",
    "wisdom",
    "dream",
    "supermarket",
    "database",
    "collection",
    "barrier",
    "project",
    "sunlight",
    "figure",
    "graph",
    "battle",
    "hundred",
    "signal",
    "thousand",
    "transformation",
    "daughter",
    "flower",
    "communication",
    "microwave",
    "electronic",
    "peace",
    "wireless",
    "delete",
    "wind",
    "brain",
    "control",
    "prophet",
    "freedom",
    "harbour",
    "confidence",
    "positive",
    "harvest",
    "hunger",
    "woman",
    "children",
    "stranger",
    "garden",
    "pleasure",
    "between",
    "recognition",
    "tomorrow",
    "autumn",
    "monkey",
    "spring",
    "winter",
    "classification",
    "typewriter",
    "success",
    "difference",
    "acoustics",
    "astronomy",
    "agreement",
    "sorrow",
    "christmas",
    "silver",
    "birthday",
    "championship",
    "comfortable",
    "diffusion",
    "murder",
    "policeman",
    "science",
    "desert",
    "basketball",
    "blood",
    "funeral",
    "silence",
    "garment",
    "merchant",
    "spirit",
    "punishment",
    "measurement",
    "ocean",
    "digital",
    "illusion",
    "tyrant",
    "castle",
    "passion",
    "magician",
    "remedy",
    "knowledge",
    "threshold",
    "number",
    "vision",
    "expectation",
    "absence",
    "mystery",
    "morning",
    "mountain",
    "treasure",
    "machine",
    "whispering",
    "eternity",
    "reflection",
    "achievement",
    "lightning",
    "secret",
    "environment",
    "shepherd",
    "confusion",
    "grave",
    "promise",
    "honour",
    "reward",
    "temple",
    "distance",
    "eagle",
    "saturn",
    "finger",
    "belief",
    "crystal",
    "fashion",
    "direction",
    "captain",
    "moment",
    "permission",
    "logic",
    "analysis",
    "password",
    "english",
    "equalizer",
    "emotion",
    "battle",
    "expression",
    "scissors",
    "trousers",
    "glasses",
    "dictionary",
    "chemistry",
    "induction",
    "detail",
    "widow",
    "wealth",
    "health",
    "disaster",
    "volcano",
    "poverty",
    "limitation",
    "perfect",
    "intelligence",
    "failure",
    "ignorance",
    "destination",
    "source",
    "resort",
    "satisfaction",
    "exam",
    "frequency",
    "selection",
    "substitution",
    "kingdom",
    "pattern",
    "management",
    "situation",
    "multiply",
    "treatment",
    "dollar",
    "intuition",
    "chapter",
    "magnet",
    "desire",
    "command",
    "action",
    "consciousness",
    "enemy",
    "security",
    "object",
    "happen",
    "happiness",
    "worry",
    "method",
    "tolerance",
    "error",
    "hesitation",
    "record",
    "tongue",
    "supply",
    "vibration",
    "stress",
    "despair",
    "restaurant",
    "television",
    "video",
    "audio",
    "layer",
    "mixture",
    "doorbell",
    "cousin",
    "finance",
    "production",
    "invisible",
    "excitement",
    "afternoon",
    "office",
    "illustration",
    "valley",
    "apartment",
    "necessary",
    "shortage",
    "almost",
    "blanket",
    "suggestion",
    "overflow",
    "demonstration",
    "challenge",
    "compact",
    "tower",
    "question",
    "problem",
    "pressure",
    "beast",
    "encouragement",
    "afraid",
    "cavity",
    "appearance",
    "wonderful",
    "matter",
    "dimension",
    "business",
    "doubt",
    "conversation",
    "reaction",
    "psychology",
    "superstition",
    "smash",
    "horseshoe",
    "surprise",
    "nothing",
    "ladder",
    "opposite",
    "reality",
    "genius",
    "string",
    "destruction",
    "expensive",
    "painting",
    "chicken",
    "wishing",
    "profession",
    "hatred",
    "possession",
    "criticism",
    "zebra",
    "harmony",
    "personality",
    "addition",
    "subtraction",
    "cipher",
    "encryption",
    "compression",
    "extension",
    "blessing",
    "meeting",
    "difficulty",
    "weapon",
    "against",
    "external",
    "internal",
    "legend",
    "servant",
    "secondary",
    "attraction",
    "sensitivity",
    "magnification",
    "someone",
    "symptom",
    "recipe",
    "service",
    "family",
    "island",
    "planet",
    "butterfly",
    "diving",
    "strength",
    "extreme",
    "opportunity",
    "illumination",
    "cable",
    "conflict",
    "interference",
    "receiver",
    "transmitter",
    "channel",
    "company",
    "grocery",
    "devil",
    "angel",
    "exactly",
    "document",
    "tutorial",
    "sound",
    "voice",
    "abbreviation",
    "abdomen",
    "abrupt",
    "absolute",
    "absorption",
    "abstract",
    "academy",
    "acceleration",
    "accident",
    "account",
    "acidification",
    "actress",
    "adaptation",
    "addiction",
    "adjustment",
    "admiration",
    "adoption",
    "advanced",
    "adventure",
    "advertisement",
    "agenda",
    "airport",
    "algorithm",
    "allocation",
    "aluminium",
    "ambiguity",
    "amphibian",
    "anaesthesia",
    "analogy",
    "anchor",
    "animation",
    "anode",
    "cathode",
    "apparent",
    "appendix",
    "approval",
    "approximation",
    "arbitrary",
    "architecture",
    "arithmetic",
    "arrangement",
    "article",
    "ascending",
    "ashamed",
    "asleep",
    "assembly",
    "astonishment",
    "atmosphere",
    "awful",
    "bachelor",
    "backbone",
    "bacteria",
    "balance",
    "balloon",
    "banana",
    "barbecue",
    "baseball",
    "beaker",
    "beggar",
    "behaviour",
    "benefit",
    "bidirectional",
    "biology",
    "blackboard",
    "bladder",
    "bleeding",
    "blender",
    "bonus",
    "bottle",
    "bracket",
    "branch",
    "bubble",
    "bucket",
    "budget",
    "bullet",
    "burglar",
    "butcher",
    "bypass",
    "calculator",
    "calibration",
    "campaign",
    "cancellation",
    "candidate",
    "candle",
    "carpenter",
    "carriage",
    "cartoon",
    "cascade",
    "casual",
    "catalyst",
    "category",
    "cement",
    "ceremony",
    "chairman",
    "checkout",
    "chimney",
    "chocolate",
    "cigarette",
    "circumference",
    "civilization",
    "classroom",
    "clearance",
    "client",
    "coconut",
    "coincidence",
    "colleague",
    "comfortable",
    "competition",
    "kangaroo",
    "kidnap",
    "journal",
    "jockey",
    "iteration",
    "isometric",
    "isolation",
    "invitation",
    "institution",
    "injection",
    "humanity",
    "housekeeper",
    "history",
    "heaven",
    "greenhouse",
    "glory",
    "foundation",
    "formula",
    "fluctuation",
    "fiction",
    "emission",
    "elasticity",
    "earthquake",
    "dynamic",
    "doctorate",
    "divorce",
    "nightmare",
    "virtue",
    "description",
  ];
  var hang_output = document.getElementById("hangman-canvas");
  var word = words[Math.floor(Math.random() * words.length)];
  console.log(
    "Hangman ready, " + words.length + " total words loaded - word is " + word
  );
  guessed = [];
  hang_output.innerHTML =
    "______<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>|<br>|<br>|<br>|<br>|_______<br>";

  for (var i = 0; i < word.length; i++) {
    hang_output.insertAdjacentHTML("beforeend", "_ ");
  }
  hang_output.insertAdjacentHTML("beforeend", "<br><br>");

  var score = 0;

  document.getElementById("hangman").addEventListener("submit", function () {
    event.preventDefault();

    const inputval = document.getElementById("selection").value;
    document.getElementById("selection").value = "";

    if (guessed.indexOf(inputval, 0) == -1 && inputval.length == 1) {
      // essentially if the guess has not been guessed yet
      guessed.push(inputval);
      console.log("successful attempt!");
      if (!word.includes(inputval)) {
        score++;
      }
      switch (score) {
        case 0:
          hang_output.innerHTML =
            "______<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>|<br>|<br>|<br>|<br>|_______<br>";
          break;
        case 1:
          hang_output.innerHTML =
            "______<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;o<br>|<br>|<br>|<br>|_______<br>";
          break;
        case 2:
          hang_output.innerHTML =
            "______<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;o<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp|<br>|<br>|<br>|_______<br>";
          break;
        case 3:
          hang_output.innerHTML =
            "______<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;o<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/|<br>|<br>|<br>|_______<br>";
          break;
        case 4:
          hang_output.innerHTML =
            "______<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;o<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/|\\<br>|<br>|<br>|_______<br>";
          break;
        case 5:
          hang_output.innerHTML =
            "______<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;o<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/|\\<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/<br>|<br>|_______<br>";
          break;
        case 6:
          hang_output.innerHTML =
            "______<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;o<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/|\\<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/\\<br>|<br>|_______<br>";
          break;
      }
      var timesMissed = 0;
      for (var i = 0; i < word.length; i++) {
        if (guessed.indexOf(word[i]) != -1) {
          hang_output.insertAdjacentHTML("beforeend", word[i] + " ");
        } else {
          hang_output.insertAdjacentHTML("beforeend", "_ ");
          timesMissed++;
        }
      }
      if (!timesMissed) {
        hang_output.insertAdjacentHTML(
          "beforeend",
          "<br>Congratulations! You won! Word was " + word
        );
      } else if (score >= 6) {
        hang_output.insertAdjacentHTML(
          "beforeend",
          "<br>You lose! Word was " + word
        );
      } else {
        hang_output.insertAdjacentHTML("beforeend", "<br><br>");
      }
    }
  });
  document
    .getElementById("reset-hangman")
    .addEventListener("click", function () {
      word = words[Math.floor(Math.random() * words.length)];
      guessed = [];
      score = 0;
      hang_output.innerHTML =
        "______<br>|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>|<br>|<br>|<br>|<br>|_______<br>";
      for (var i = 0; i < word.length; i++) {
        hang_output.insertAdjacentHTML("beforeend", "_ ");
      }
      hang_output.insertAdjacentHTML("beforeend", "<br><br>");
    });
});
